### ISSUE TITLE
make gives me this error

### ISSUE THREAD

**Issue by vash15** [elmarco/wixl#2]
Hi, i'm compiling using Ubuntu 13 server. Any idea ? Tnks.
make --no-print-directory all-recursive
Making all in src
  VALAC    wixl_vala.stamp
/bin/bash: valac: command not found
make[2]: *** [wixl_vala.stamp] Error 127
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by elmarco** [comment]
closing, hopefully you managed to build it.
if not, you can open a bug at https://bugzilla.gnome.org/enter_bug.cgi?product=msitools
