### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by slifin** [elmarco/wixl#3]
I'd like to use this to change msi properties on an already compiled .msi file on a linux server I think I could probably muddle through make if I had a list of things that this depends on and some blind luck but no idea how I would tell wixl to recompile my msi file with new properties 

Is there any documentation on the above?

**Comment by elmarco** [comment]
Hi

Please use gnome bugzilla for bug reports: https://bugzilla.gnome.org/enter_bug.cgi?product=msitools

You can't use wixl to modify properties of a MSI. Wixl is meant to build MSI from .wix xml description files.

However, you should be able to modify a MSI with msibuild (perhaps with msidump help to extract tables). Further modification should be possible by using the API. You'll have to investigate a bit :)
